### ISSUE TITLE
Building Dockerfile issue

### ISSUE THREAD

**Issue by relvan1** [pwittchen/ydocker#7]
Hi,

When I try to build the docker file its throwing some kind of errors like cp stat not found and I resolved those things. But now, the script failing at this step "RUN $yHYBRIS_DIR/Hybris5.7/installer/install.sh". please advise on this issue.

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting the issue. It's not official Hybris product and you need to have an e-mail account in SAP domain and access to the Artifactory in order to build Docker container. Otherwise, you won't be able to build it. Moreover, I haven't tested it with the older Hybris versions.

Regards,
Piotr

**Comment by relvan1** [comment]
Artifactory means..

**Comment by relvan1** [comment]
After getting the SAP email. What should I do..

**Comment by pwittchen** [comment]
It's internal repository for Hybris projects. SAP admins are responsible for providing appropriate permissions. I don't have access to that. It's not available for the external world. Please do not use project from this repo in production! It's just an experimental Proof of Concept.
